### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [VivekVithlani/QRCodeReader#3]
```
This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
```

**Comment by VivekVithlani** [comment]
Camera :

Key       :  Privacy - Camera Usage Description   
Value   :  $(PRODUCT_NAME) camera use

You need to add key value in info.plist file.
How to add key in info.plist [check here](https://stackoverflow.com/questions/38498275/ios-10-changes-in-asking-permissions-of-camera-microphone-and-photo-library-c)

If you face any issue please let me know.

Thank you,
Vivek Vithalani.
